name: mug_hybrid_multiposition

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    agentview_image:
      shape: [3, 84, 84]
      type: rgb
    robot0_eye_in_hand_image:
      shape: [3, 84, 84]
      type: rgb
    robot0_eef_pos:
      shape: [3]
      # type default: low_dim
    robot0_eef_quat:
      shape: [4]
    robot0_gripper_qpos:
      shape: [2]
  action: 
    shape: [7]

env_runner:
  _target_: diffusion_policy.env_runner.robomimic_openpi_runner.RobomimicOpenPIRunner
  output_dir: 
  dataset_path: /tmp/core_datasets/mug_cleanup/demo_src_mug_cleanup_task_D0/demo.hdf5
  shape_meta: *shape_meta
  # costs 1GB per env
  n_train: 6
  n_train_vis: 2
  train_start_idx: 0
  n_test: 50
  n_test_vis: 4
  test_start_seed: 100000
  # use python's eval function as resolver, single-quoted string as argument
  max_steps: 400
  n_obs_steps: 2
  # n_action_steps: 16
  n_action_steps: 8
  render_obs_key: 'agentview_image'
  fps: 10
  crf: 22
  past_action: False
  abs_action: False
  tqdm_interval_sec: 1.0
  n_envs: 28
  env_name: MugCleanup_D0
  rotation_rep: 'rotation_6d'
  if_mask: False
  ip: "127.0.0.1"
  port: 8000
  prompt: "pick up the mug into the desk"
# evaluation at this config requires a 16 core 64GB instance.
