name: square_image

image_shape: [3, 240, 426]
base_dataset_path: &base_dataset_path /data1/dataset
dataset_path_list: &dataset_path_list
  - writing
  - writing_a
  - writing_circle
  - writing_circle_inv
  - writing_cross
  - writing_random
  - writing_rec
  - writing_t
  - writing_tri

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    human:
      shape: ${task.image_shape}
      type: rgb
    # robot:
    #   shape: ${task.image_shape}
    #   type: rgb
    # robot0_eef_pos:
    #   shape: [3]
    #   # type default: low_dim
    # robot0_eef_rot_pos:
    #   shape: [3]
    # robot0_gripper_qpos:
    #   shape: [1]
  action: 
    shape: [10]

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.h2r_dataset.H2RDataset
  shape_meta: *shape_meta
  dataset_path_list: *dataset_path_list
  base_dataset_path: *base_dataset_path
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: True
  rotation_rep: 'rotation_6d'
  use_legacy_normalizer: False
  use_cache: True
  seed: 42
  val_ratio: 0.02
  sample_rate: 4
